### ISSUE TITLE
Use YouTube poster for image thumb in Craft 5 CP element cards

### ISSUE THREAD

**Issue by chrisrowe** [benjamminf/craft-embedded-assets#283]
### What would you like to see added to or changed in Embedded Assets, and why?

When choosing a YouTube embed the Craft 5 element card image shows the JSON file type, it'd be great if this plugin could instead use the poster (the image propery) from within this file?

**Comment by ttempleton** [comment]
This should be working already - is the image showing in the assets index? If so, could you please post an example of a YouTube video that's not showing the image on the card?

**Comment by chrisrowe** [comment]
Aha thank you, yes it works for local filesystems but it seems that it's not working on a site staged on Servd https://servd.host/ their assets are stored offsite on an S3 compatible CDN.

Looking at `_configureAssetThumbnails()` it appears the `$thumbnailUrl` is correct and `$event->url` is being updated but the front end still shows the JSON file SVG, nothing of interest in the log files either. Any ideas or things to look out for?

**Comment by ttempleton** [comment]
I've run a test with an (admittedly different) S3 service and that's worked for me. I'll ask my colleagues if they've noticed any issues, but I have a couple of questions just to try to narrow down the cause:

- Do thumbnails work as expected for embedded asset types other than YouTube?
- Do they work as expected when using an assets field with a list or large thumbnail view mode?

**Comment by chrisrowe** [comment]
Huh, has to be a Servd thing then, probably because files are publically avalible without a key which the Servd plugin handles when using getUrl. Here's a video with some more clues, (the dev volume is local) https://up.chri.sr/Screen-Recording-2024-11-18-11-39-08-1731929948.mp4.

Confirming thumbnails don't work with other view modes or in an asset field.

I poked around in your plugin code and was able to get the ytimg.com to output when debugging but I guess something else is going on

**Comment by jamie-s-white** [comment]
Can confirm this is still happening for ourselves when using this plugin on our Servd projects.
